services:
  - type: web
    name: avito-advertisements
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import init_app; init_app()"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: avito-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    plan: free 